const forecast = [            {
    "date": "2023-11-20",
    "date_epoch": 1700438400,
    "day": {
        "maxtemp_c": 10.3,
        "maxtemp_f": 50.5,
        "mintemp_c": 3.4,
        "mintemp_f": 38.1,
        "avgtemp_c": 7.1,
        "avgtemp_f": 44.8,
        "maxwind_mph": 6.5,
        "maxwind_kph": 10.4,
        "totalprecip_mm": 0.0,
        "totalprecip_in": 0.0,
        "totalsnow_cm": 0.0,
        "avgvis_km": 10.0,
        "avgvis_miles": 6.0,
        "avghumidity": 80.0,
        "daily_will_it_rain": 0,
        "daily_chance_of_rain": 0,
        "daily_will_it_snow": 0,
        "daily_chance_of_snow": 0,
        "condition": {
            "text": "Overcast",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
            "code": 1009
        },
        "uv": 2.0
    },
    "astro": {
        "sunrise": "07:31 AM",
        "sunset": "04:25 PM",
        "moonrise": "01:51 PM",
        "moonset": "No moonset",
        "moon_phase": "First Quarter",
        "moon_illumination": 45,
        "is_moon_up": 1,
        "is_sun_up": 1
    },
    "hour": [
        {
            "time_epoch": 1700467200,
            "time": "2023-11-20 00:00",
            "temp_c": 4.1,
            "temp_f": 39.4,
            "is_day": 0,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
            },
            "wind_mph": 2.5,
            "wind_kph": 4.0,
            "wind_degree": 64,
            "wind_dir": "ENE",
            "pressure_mb": 1033.0,
            "pressure_in": 30.51,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 91,
            "cloud": 28,
            "feelslike_c": 4.1,
            "feelslike_f": 39.4,
            "windchill_c": 4.1,
            "windchill_f": 39.4,
            "heatindex_c": 4.1,
            "heatindex_f": 39.4,
            "dewpoint_c": 2.8,
            "dewpoint_f": 37.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.0,
            "gust_kph": 6.5,
            "uv": 1.0
        },
        {
            "time_epoch": 1700470800,
            "time": "2023-11-20 01:00",
            "temp_c": 3.4,
            "temp_f": 38.1,
            "is_day": 0,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 73,
            "wind_dir": "ENE",
            "pressure_mb": 1033.0,
            "pressure_in": 30.52,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 92,
            "cloud": 35,
            "feelslike_c": 2.4,
            "feelslike_f": 36.3,
            "windchill_c": 2.4,
            "windchill_f": 36.3,
            "heatindex_c": 3.4,
            "heatindex_f": 38.1,
            "dewpoint_c": 2.2,
            "dewpoint_f": 36.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 6.1,
            "gust_kph": 9.8,
            "uv": 1.0
        },
        {
            "time_epoch": 1700474400,
            "time": "2023-11-20 02:00",
            "temp_c": 4.5,
            "temp_f": 40.1,
            "is_day": 0,
            "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 70,
            "wind_dir": "ENE",
            "pressure_mb": 1033.0,
            "pressure_in": 30.51,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 96,
            "cloud": 71,
            "feelslike_c": 2.7,
            "feelslike_f": 36.8,
            "windchill_c": 2.7,
            "windchill_f": 36.8,
            "heatindex_c": 4.5,
            "heatindex_f": 40.1,
            "dewpoint_c": 4.0,
            "dewpoint_f": 39.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 8.0,
            "gust_kph": 12.9,
            "uv": 1.0
        },
        {
            "time_epoch": 1700478000,
            "time": "2023-11-20 03:00",
            "temp_c": 4.6,
            "temp_f": 40.3,
            "is_day": 0,
            "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 72,
            "wind_dir": "ENE",
            "pressure_mb": 1034.0,
            "pressure_in": 30.52,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 96,
            "cloud": 66,
            "feelslike_c": 2.8,
            "feelslike_f": 37.0,
            "windchill_c": 2.8,
            "windchill_f": 37.0,
            "heatindex_c": 4.6,
            "heatindex_f": 40.3,
            "dewpoint_c": 4.0,
            "dewpoint_f": 39.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.2,
            "gust_kph": 14.9,
            "uv": 1.0
        },
        {
            "time_epoch": 1700481600,
            "time": "2023-11-20 04:00",
            "temp_c": 4.9,
            "temp_f": 40.8,
            "is_day": 0,
            "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 75,
            "wind_dir": "ENE",
            "pressure_mb": 1034.0,
            "pressure_in": 30.52,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 96,
            "cloud": 82,
            "feelslike_c": 2.9,
            "feelslike_f": 37.3,
            "windchill_c": 2.9,
            "windchill_f": 37.3,
            "heatindex_c": 4.9,
            "heatindex_f": 40.8,
            "dewpoint_c": 4.3,
            "dewpoint_f": 39.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.3,
            "gust_kph": 15.0,
            "uv": 1.0
        },
        {
            "time_epoch": 1700485200,
            "time": "2023-11-20 05:00",
            "temp_c": 5.2,
            "temp_f": 41.4,
            "is_day": 0,
            "condition": {
                "text": "Mist",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                "code": 1030
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 90,
            "wind_dir": "E",
            "pressure_mb": 1033.0,
            "pressure_in": 30.51,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 95,
            "cloud": 91,
            "feelslike_c": 3.1,
            "feelslike_f": 37.6,
            "windchill_c": 3.1,
            "windchill_f": 37.6,
            "heatindex_c": 5.2,
            "heatindex_f": 41.4,
            "dewpoint_c": 4.4,
            "dewpoint_f": 40.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.9,
            "gust_kph": 17.6,
            "uv": 1.0
        },
        {
            "time_epoch": 1700488800,
            "time": "2023-11-20 06:00",
            "temp_c": 5.4,
            "temp_f": 41.7,
            "is_day": 0,
            "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 88,
            "wind_dir": "E",
            "pressure_mb": 1033.0,
            "pressure_in": 30.52,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 94,
            "cloud": 96,
            "feelslike_c": 3.6,
            "feelslike_f": 38.5,
            "windchill_c": 3.6,
            "windchill_f": 38.5,
            "heatindex_c": 5.4,
            "heatindex_f": 41.7,
            "dewpoint_c": 4.4,
            "dewpoint_f": 40.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 11.3,
            "gust_kph": 18.2,
            "uv": 1.0
        },
        {
            "time_epoch": 1700492400,
            "time": "2023-11-20 07:00",
            "temp_c": 5.6,
            "temp_f": 42.1,
            "is_day": 0,
            "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 85,
            "wind_dir": "E",
            "pressure_mb": 1034.0,
            "pressure_in": 30.53,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 92,
            "cloud": 96,
            "feelslike_c": 3.7,
            "feelslike_f": 38.6,
            "windchill_c": 3.7,
            "windchill_f": 38.6,
            "heatindex_c": 5.6,
            "heatindex_f": 42.1,
            "dewpoint_c": 4.4,
            "dewpoint_f": 40.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 10.9,
            "gust_kph": 17.5,
            "uv": 1.0
        },
        {
            "time_epoch": 1700496000,
            "time": "2023-11-20 08:00",
            "temp_c": 5.0,
            "temp_f": 41.0,
            "is_day": 1,
            "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 77,
            "wind_dir": "ENE",
            "pressure_mb": 1033.0,
            "pressure_in": 30.51,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 91,
            "cloud": 99,
            "feelslike_c": 2.7,
            "feelslike_f": 36.9,
            "windchill_c": 2.7,
            "windchill_f": 36.9,
            "heatindex_c": 5.0,
            "heatindex_f": 41.0,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.4,
            "uv": 2.0
        },
        {
            "time_epoch": 1700499600,
            "time": "2023-11-20 09:00",
            "temp_c": 5.2,
            "temp_f": 41.4,
            "is_day": 1,
            "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
            },
            "wind_mph": 5.4,
            "wind_kph": 8.6,
            "wind_degree": 80,
            "wind_dir": "E",
            "pressure_mb": 1033.0,
            "pressure_in": 30.51,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 90,
            "cloud": 100,
            "feelslike_c": 2.9,
            "feelslike_f": 37.2,
            "windchill_c": 2.9,
            "windchill_f": 37.2,
            "heatindex_c": 5.2,
            "heatindex_f": 41.4,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 9.6,
            "gust_kph": 15.4,
            "uv": 2.0
        },
        {
            "time_epoch": 1700503200,
            "time": "2023-11-20 10:00",
            "temp_c": 5.6,
            "temp_f": 42.1,
            "is_day": 1,
            "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
            },
            "wind_mph": 3.6,
            "wind_kph": 5.8,
            "wind_degree": 82,
            "wind_dir": "E",
            "pressure_mb": 1033.0,
            "pressure_in": 30.52,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 87,
            "cloud": 98,
            "feelslike_c": 3.4,
            "feelslike_f": 38.0,
            "windchill_c": 3.4,
            "windchill_f": 38.0,
            "heatindex_c": 5.6,
            "heatindex_f": 42.1,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 5.8,
            "gust_kph": 9.3,
            "uv": 2.0
        },
        {
            "time_epoch": 1700506800,
            "time": "2023-11-20 11:00",
            "temp_c": 6.3,
            "temp_f": 43.3,
            "is_day": 1,
            "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                "code": 1006
            },
            "wind_mph": 3.1,
            "wind_kph": 5.0,
            "wind_degree": 69,
            "wind_dir": "ENE",
            "pressure_mb": 1033.0,
            "pressure_in": 30.49,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 84,
            "cloud": 73,
            "feelslike_c": 4.2,
            "feelslike_f": 39.6,
            "windchill_c": 4.2,
            "windchill_f": 39.6,
            "heatindex_c": 6.3,
            "heatindex_f": 43.3,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 4.7,
            "gust_kph": 7.6,
            "uv": 2.0
        },
        {
            "time_epoch": 1700510400,
            "time": "2023-11-20 12:00",
            "temp_c": 7.4,
            "temp_f": 45.3,
            "is_day": 1,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 58,
            "wind_dir": "ENE",
            "pressure_mb": 1032.0,
            "pressure_in": 30.49,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 78,
            "cloud": 60,
            "feelslike_c": 5.7,
            "feelslike_f": 42.3,
            "windchill_c": 5.7,
            "windchill_f": 42.3,
            "heatindex_c": 7.4,
            "heatindex_f": 45.3,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.2,
            "gust_kph": 3.6,
            "uv": 3.0
        },
        {
            "time_epoch": 1700514000,
            "time": "2023-11-20 13:00",
            "temp_c": 8.6,
            "temp_f": 47.5,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 133,
            "wind_dir": "SE",
            "pressure_mb": 1032.0,
            "pressure_in": 30.47,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 24,
            "feelslike_c": 7.4,
            "feelslike_f": 45.3,
            "windchill_c": 7.4,
            "windchill_f": 45.3,
            "heatindex_c": 8.6,
            "heatindex_f": 47.5,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.9,
            "gust_kph": 3.0,
            "uv": 3.0
        },
        {
            "time_epoch": 1700517600,
            "time": "2023-11-20 14:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 157,
            "wind_dir": "SSE",
            "pressure_mb": 1031.0,
            "pressure_in": 30.44,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 74,
            "cloud": 18,
            "feelslike_c": 8.5,
            "feelslike_f": 47.2,
            "windchill_c": 8.5,
            "windchill_f": 47.2,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 5.2,
            "dewpoint_f": 41.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.9,
            "gust_kph": 3.0,
            "uv": 3.0
        },
        {
            "time_epoch": 1700521200,
            "time": "2023-11-20 15:00",
            "temp_c": 10.5,
            "temp_f": 50.9,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 191,
            "wind_dir": "SSW",
            "pressure_mb": 1030.0,
            "pressure_in": 30.41,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 73,
            "cloud": 10,
            "feelslike_c": 9.7,
            "feelslike_f": 49.4,
            "windchill_c": 9.7,
            "windchill_f": 49.4,
            "heatindex_c": 10.5,
            "heatindex_f": 50.9,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.9,
            "gust_kph": 3.0,
            "uv": 4.0
        },
        {
            "time_epoch": 1700524800,
            "time": "2023-11-20 16:00",
            "temp_c": 9.9,
            "temp_f": 49.8,
            "is_day": 1,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 202,
            "wind_dir": "SSW",
            "pressure_mb": 1029.0,
            "pressure_in": 30.4,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 48,
            "feelslike_c": 9.2,
            "feelslike_f": 48.5,
            "windchill_c": 9.2,
            "windchill_f": 48.5,
            "heatindex_c": 9.9,
            "heatindex_f": 49.8,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.3,
            "gust_kph": 3.8,
            "uv": 3.0
        },
        {
            "time_epoch": 1700528400,
            "time": "2023-11-20 17:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 0,
            "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
            },
            "wind_mph": 1.1,
            "wind_kph": 1.8,
            "wind_degree": 248,
            "wind_dir": "WSW",
            "pressure_mb": 1028.0,
            "pressure_in": 30.36,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 77,
            "cloud": 70,
            "feelslike_c": 8.8,
            "feelslike_f": 47.8,
            "windchill_c": 8.8,
            "windchill_f": 47.8,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.9,
            "gust_kph": 3.1,
            "uv": 1.0
        },
        {
            "time_epoch": 1700532000,
            "time": "2023-11-20 18:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 0,
            "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 7,
            "wind_dir": "N",
            "pressure_mb": 1028.0,
            "pressure_in": 30.35,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 75,
            "cloud": 71,
            "feelslike_c": 8.5,
            "feelslike_f": 47.3,
            "windchill_c": 8.5,
            "windchill_f": 47.3,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 5.6,
            "dewpoint_f": 42.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.4,
            "gust_kph": 3.9,
            "uv": 1.0
        },
        {
            "time_epoch": 1700535600,
            "time": "2023-11-20 19:00",
            "temp_c": 9.6,
            "temp_f": 49.3,
            "is_day": 0,
            "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
            },
            "wind_mph": 1.8,
            "wind_kph": 2.9,
            "wind_degree": 32,
            "wind_dir": "NNE",
            "pressure_mb": 1027.0,
            "pressure_in": 30.33,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 66,
            "feelslike_c": 8.2,
            "feelslike_f": 46.8,
            "windchill_c": 8.2,
            "windchill_f": 46.8,
            "heatindex_c": 9.6,
            "heatindex_f": 49.3,
            "dewpoint_c": 4.9,
            "dewpoint_f": 40.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.3,
            "gust_kph": 5.3,
            "uv": 1.0
        },
        {
            "time_epoch": 1700539200,
            "time": "2023-11-20 20:00",
            "temp_c": 9.0,
            "temp_f": 48.2,
            "is_day": 0,
            "condition": {
                "text": "Cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                "code": 1006
            },
            "wind_mph": 1.6,
            "wind_kph": 2.5,
            "wind_degree": 14,
            "wind_dir": "NNE",
            "pressure_mb": 1027.0,
            "pressure_in": 30.32,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 68,
            "cloud": 66,
            "feelslike_c": 7.4,
            "feelslike_f": 45.4,
            "windchill_c": 7.4,
            "windchill_f": 45.4,
            "heatindex_c": 9.0,
            "heatindex_f": 48.2,
            "dewpoint_c": 3.4,
            "dewpoint_f": 38.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 3.0,
            "gust_kph": 4.8,
            "uv": 1.0
        },
        {
            "time_epoch": 1700542800,
            "time": "2023-11-20 21:00",
            "temp_c": 3.0,
            "temp_f": 37.4,
            "is_day": 0,
            "condition": {
                "text": "Partly cloudy",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                "code": 1003
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 10,
            "wind_dir": "N",
            "pressure_mb": 1028.0,
            "pressure_in": 30.35,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 93,
            "cloud": 75,
            "feelslike_c": 7.6,
            "feelslike_f": 45.6,
            "windchill_c": 7.6,
            "windchill_f": 45.6,
            "heatindex_c": 9.0,
            "heatindex_f": 48.2,
            "dewpoint_c": 2.3,
            "dewpoint_f": 36.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 32.0,
            "vis_miles": 19.0,
            "gust_mph": 2.6,
            "gust_kph": 4.2,
            "uv": 1.0
        },
        {
            "time_epoch": 1700546400,
            "time": "2023-11-20 22:00",
            "temp_c": 8.7,
            "temp_f": 47.7,
            "is_day": 0,
            "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
            },
            "wind_mph": 0.9,
            "wind_kph": 1.4,
            "wind_degree": 337,
            "wind_dir": "NNW",
            "pressure_mb": 1025.0,
            "pressure_in": 30.28,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 60,
            "cloud": 98,
            "feelslike_c": 7.3,
            "feelslike_f": 45.1,
            "windchill_c": 7.3,
            "windchill_f": 45.1,
            "heatindex_c": 8.7,
            "heatindex_f": 47.7,
            "dewpoint_c": 1.5,
            "dewpoint_f": 34.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 1.7,
            "gust_kph": 2.7,
            "uv": 1.0
        },
        {
            "time_epoch": 1700550000,
            "time": "2023-11-20 23:00",
            "temp_c": 8.5,
            "temp_f": 47.3,
            "is_day": 0,
            "condition": {
                "text": "Overcast",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                "code": 1009
            },
            "wind_mph": 1.3,
            "wind_kph": 2.2,
            "wind_degree": 52,
            "wind_dir": "NE",
            "pressure_mb": 1025.0,
            "pressure_in": 30.27,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 57,
            "cloud": 100,
            "feelslike_c": 7.0,
            "feelslike_f": 44.7,
            "windchill_c": 7.0,
            "windchill_f": 44.7,
            "heatindex_c": 8.5,
            "heatindex_f": 47.3,
            "dewpoint_c": 0.5,
            "dewpoint_f": 33.0,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "gust_mph": 2.6,
            "gust_kph": 4.1,
            "uv": 1.0
        }
    ]
},]
module.exports = {
    forecast
}